language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: UdDtzJwrtHOaFlqsWOVwoh+kpWouWM44FYpx5MDjZrl4aoIhMIv1EtnUT0En3II8lZkDHsyjnOoQsNHz6wRHT7mFBUIrZ3lzrcINamcDu1v6eB8swneeqdsddau/lYX3seySOEkr3CLkfVXRzKcp5T5LCI7WSFiWP9Adi4A0FzhvEfPFbJmrpVU/57DNr7ErNdFpw8FD4zx8i4zmp9zVJn49HeBMMBhq7B/459K41DXZVzeBYggROo+JKiq7bqb91JAttUiEPcKl9XewXRCuQdLO+twZRJs2r1W1PDT6V68e5nHYbaEFlYTYKZ36AcAU6qzSmhkD0kr3k46K2gFfWUPdfsPF0BJPLfNPyzAtTIncE7zhnHDnVrbX5x08T8hqiSFzl257onqboEoeG/IT6vWedZfuqsRMtQ0Sq6SKne5h72JvJfGrbMlgoMrx9Y9mOBRaqSlGbU5SPGq8TkraW8p7mJDdfnK++CTd6as6rulffEfRSO48K0xrbOU9KP8A0ZEz+TmawplqKJHlZ/Jg3VKzUJxd6TEXgQJpBXHEzmRpiIctUoIzFn212M+81LZ6WBQiX5GlcBVQDRWdSxxL9oRNBnO+f8ugVdu7lwAPSqP9TSEeK+4PODg8DVvLw/o4kJWaW3qarPL2QINJ6gCpmWpJdREaFvOAyS7oZBV/GsY=
  app: letsplayapp
  on:
    repo: megmatty/letsplay-fullstack
    branch: apiupdate
